### ISSUE TITLE
FEAT: Gerar a modelagem do django pelo proprio app

### ISSUE THREAD

**Issue by AnthonyLoche** [2info2-Grupo-3/BackendManutencao#13]
Baixar as dependencias para criar a foto de modelagem do django

Criar uma foto da modelagem atual

Criar um script que faz ele gerar a model sozinha

Criar uma pasta de fotos de modelage, para futuras modificações na modelagem

**Comment by jonatasperaza** [comment]
## Agora há dois comandos para gerar o modelo

- pdm setup: Instala as dependências para gerar a modelagem de acordo com o seu sistema  para não termos problemas futuros com pacotes
- pdm model gera o arquivo models.png
- Há uma pasta chamada img que tera as modelagens, nome das modelagens deverá ser o dia que ela foi feita como por exemplo 19-07.png



![Image](https://github.com/user-attachments/assets/2e3c5455-91c8-45f9-8a11-986398d1eeb3)

### Modelagem



![Image](https://github.com/user-attachments/assets/5682b4d2-9b16-4d7b-8349-d80359fb691c)
